apiVersion: v1
kind: Pod
metadata:
  name: two-containers-rhel
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: rhel-container-1
    image: rhel7.7
    volumeMounts:
    - name: shared-data
      mountPath: /test
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the rhel container > /test/test.txt"]


  - name: rhel-container-2
    image: rhel7.7
    volumeMounts:
    - name: shared-data
      mountPath: /test
    command: ["/bin/sh"]
    args: ["-c", "cat /test/test.txt"]
